#!/usr/bin/env python3
"""
query.py — Retrieve relevant wiki pages for a question and print them for Claude Code.

Usage:
    python scripts/query.py "your question here" [--save <answer_file>]

    --save <file>   After Claude Code answers, pass the answer back to file the
                    response into the wiki as a new page.

This script does NOT call any LLM API for the answer. Instead it:
  1. Uses gemma4:26b (local) to find which topics are relevant
  2. Loads those wiki pages
  3. Prints them to stdout in a structured format

Claude Code reads the output and synthesizes the answer directly.
No API key needed.

To file an answer back into the wiki:
    python scripts/query.py --save answer.md
"""

import argparse
import re
import sys
import sys, io

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from config import cfg
from llm import call_local
from wiki_index import (
    append_log,
    load_memory,
    slugify,
    posix_rel,
    insert_topic_entry,
    ensure_master_has_topic,
)

RELEVANCE_SYSTEM = """\
You are a search assistant for a personal knowledge wiki.
Given a question and the wiki index (Memory.md), identify which topics are most relevant.
The wiki index lists topic names as link display text, e.g. "- [Topic Name](path)".
Return ONLY valid JSON, no fences:
{
  "topics": ["Topic Name 1", "Topic Name 2"],
  "reasoning": "one sentence explaining why"
}
If no topics are clearly relevant, return {"topics": [], "reasoning": "..."}
"""

SAVE_PAGE_SYSTEM = """\
You are creating a wiki page from a Q&A exchange.
Given the question and a provided answer, write a clean wiki page that stands alone as a reference.

Return ONLY markdown, no fences:

# <Question as title>

**Date:** <today>
**Type:** Query

---

## Answer
<Clean version of the answer>

## Sources Used
<List of wiki pages cited, if known>

## Related Pages
<Leave blank>

---
*Generated by cortex query*
"""


def find_relevant_topics(question: str, memory_text: str) -> list[str]:
    prompt = f"Question: {question}\n\nMemory.md:\n{memory_text}"
    raw = call_local(prompt, RELEVANCE_SYSTEM, timeout=cfg.timeout_short, label="find topics")
    raw = re.sub(r"```[a-z]*\n?", "", raw).strip()
    try:
        import json

        result = json.loads(raw)
        topics = result.get("topics", [])
        reasoning = result.get("reasoning", "")
        if reasoning:
            print(f"  Relevance: {reasoning}", file=sys.stderr)
        return topics
    except Exception:
        return []


def load_topic_pages(topics: list[str], memory_text: str) -> list[tuple[str, str]]:
    """Load wiki pages for the given topics. Returns [(slug, content)].

    Reads master Memory.md for topic links, then per-topic Memory.md for page paths.
    """
    pages = []

    # Load _overview.md first for each relevant topic
    for topic in topics:
        overview = cfg.wiki_dir / slugify(topic) / "_overview.md"
        if overview.exists():
            content = overview.read_text(encoding="utf-8")
            pages.append((f"[overview] {topic}", content))

    # Parse master Memory.md for topic links (format: - [Topic](wiki/topic/Memory.md))
    for line in memory_text.splitlines():
        m = re.match(r"-\s+\[([^\]]+)\]\(([^)]+\.md)\)", line)
        if not m:
            continue
        topic_name = m.group(1)
        if topics and topic_name not in topics:
            continue
        topic_mem_path = cfg.vault_root / m.group(2)
        if not topic_mem_path.exists():
            continue
        topic_dir = topic_mem_path.parent
        topic_mem_text = topic_mem_path.read_text(encoding="utf-8")

        # Parse per-topic Memory.md for page paths (local paths relative to topic_dir)
        for tline in topic_mem_text.splitlines():
            tm = re.match(r"-\s+\[([^\]]+)\]\(([^)]+)\)", tline)
            if tm:
                page_path = topic_dir / tm.group(2)
                if page_path.exists():
                    content = page_path.read_text(encoding="utf-8")
                    pages.append((tm.group(1), content))

    return pages


def save_answer(question: str, answer_file: Path):
    """File an answer back into the wiki."""
    if not answer_file.exists():
        print(f"Error: answer file not found: {answer_file}", file=sys.stderr)
        sys.exit(1)

    answer_text = answer_file.read_text(encoding="utf-8").strip()
    today = date.today().isoformat()
    slug = re.sub(r"[^a-z0-9]+", "-", question.lower())[:40].strip("-")
    slug = f"query-{slug}-{today}"

    topic = "Queries & Synthesis"
    topic_folder = slugify(topic)
    topic_dir = cfg.wiki_dir / topic_folder
    topic_dir.mkdir(parents=True, exist_ok=True)

    prompt = f"Question: {question}\n\nAnswer:\n{answer_text}\n\nToday: {today}"
    page_content = call_local(prompt, SAVE_PAGE_SYSTEM, timeout=cfg.timeout_long, label="save answer")

    page_path = topic_dir / f"{slug}.md"
    page_path.write_text(page_content, encoding="utf-8")

    local_path = posix_rel(page_path.relative_to(topic_dir))
    memory_entry = f"- [{slug}]({local_path}) — Q: {question[:60]}"
    insert_topic_entry(topic_dir, memory_entry, today)
    topic_mem_rel = posix_rel((topic_dir / "Memory.md").relative_to(cfg.vault_root))
    ensure_master_has_topic(cfg.memory_md, topic, topic_mem_rel, today)

    append_log(cfg.log_md, "query-saved", f"{question[:60]} → {slug}.md")
    print(f"[ok] Answer filed: wiki/{topic_folder}/{slug}.md")


def main():
    parser = argparse.ArgumentParser(description="Retrieve wiki pages for a question")
    parser.add_argument("question", nargs="?", help="Your question")
    parser.add_argument(
        "--save",
        metavar="ANSWER_FILE",
        help="File an answer back into the wiki (provide answer as a .md file)",
    )
    args = parser.parse_args()

    cfg.ensure_dirs()

    # --save mode: just file the answer, no retrieval needed
    if args.save and not args.question:
        print("Error: --save requires a question as the first argument", file=sys.stderr)
        sys.exit(1)

    if args.save and args.question:
        save_answer(args.question, Path(args.save))
        return

    if not args.question:
        parser.print_help()
        sys.exit(1)

    memory_text = load_memory(cfg.memory_md)

    print(f"\nFinding relevant topics for: {args.question}", file=sys.stderr)
    topics = find_relevant_topics(args.question, memory_text)

    pages = load_topic_pages(topics, memory_text)

    if not pages:
        print("\n── BRAIN WIKI CONTEXT ──────────────────────────────────────")
        print(f"No relevant pages found for: {args.question}")
        print("The wiki may not have sources on this topic yet.")
        print("Consider ingesting relevant sources first.")
        print("────────────────────────────────────────────────────────────")
        append_log(cfg.log_md, "query", f"(no results) {args.question[:80]}")
        return

    # Print pages for Claude Code to read and synthesize
    print("\n── BRAIN WIKI CONTEXT ──────────────────────────────────────")
    print(f"Question: {args.question}")
    print(f"Pages loaded: {len(pages)}")
    print("────────────────────────────────────────────────────────────\n")

    for slug, content in pages:
        print(f"=== {slug} ===")
        print(content)
        print()

    print("── END BRAIN WIKI CONTEXT ──────────────────────────────────")
    print("Synthesize an answer to the question above using these pages.")
    print("Cite page names where relevant. If pages are insufficient, say so.")
    print("────────────────────────────────────────────────────────────")

    append_log(cfg.log_md, "query", args.question[:80])


if __name__ == "__main__":
    main()
