#!/usr/bin/env python3
"""
summarize_with_ollama.py — Summarize a chat using a local Ollama model.

Two input modes:
  1. Raw transcript (.txt)  — dumped from an active Claude Code session
  2. Pre-formatted .md file — an existing chat export you want to run through the flow

Usage:
    # Mode 1: raw transcript (default)
    python scripts/summarize_with_ollama.py /tmp/chat-transcript.txt [--related "path|desc" ...]

    # Mode 2: existing .md file
    python scripts/summarize_with_ollama.py chat-export.md --md [--related "path|desc" ...]

    --related can be passed multiple times, once per related session.
    --md      signals the input is already a markdown chat log, not a raw USER:/ASSISTANT: transcript.

Prints a structured markdown summary to stdout.

Requires Ollama to be running locally: https://ollama.ai
    ollama serve
    ollama pull gemma4:31b
"""

import argparse
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path
import os

_env_path = Path(__file__).parent.parent / ".env"
if _env_path.exists():
    for _line in _env_path.read_text().splitlines():
        if _line.startswith("OLLAMA_URL="):
            os.environ.setdefault("OLLAMA_URL", _line.split("=", 1)[1].strip())

OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434/api/generate")
MODEL = "gemma4:31b"

# ── System prompts ─────────────────────────────────────────────────────────────

_STRUCTURE = """\
Use this exact structure:

# Chat Summary: <short topic title>

**Date:** <extract from content or use today>
**Session Length:** <approximate message count>

---

## Overview
<2–4 sentences describing what this session covered and why>

## Topics Discussed
- <topic 1>
- <topic 2>

## Key Outcomes
<Concrete results: files created, decisions made, problems solved. Be specific.>

## Code / Files Produced
<List any scripts, files, or artifacts with one-line descriptions. Omit section if none.>

{related_section}

## Action Items / Next Steps
<Tasks the user indicated they want to do next. Omit section if none.>

---
*Summary generated by gemma4:31b via Ollama*
"""

_RELATED_PLACEHOLDER = "## Related Sessions\n<Omit this section — no related sessions provided.>"

_RELATED_INSTRUCTIONS = """\
## Related Sessions
<Use the related sessions list provided to write markdown links. For each write:
- [session-slug](relative/path.md) — one sentence on how it connects to THIS session
Order chronologically if dates are available.>"""

SYSTEM_RAW = (
    "You are a precise note-taker. Given a raw AI chat transcript "
    "(lines prefixed USER: / ASSISTANT:), produce a structured markdown summary.\n\n"
    "Return ONLY the markdown — no preamble, no backtick fences, no extra commentary.\n\n"
    + _STRUCTURE.format(related_section=_RELATED_PLACEHOLDER)
)

SYSTEM_RAW_RELATED = (
    "You are a precise note-taker. Given a raw AI chat transcript and a list of related "
    "past sessions, produce a structured markdown summary.\n\n"
    "Return ONLY the markdown — no preamble, no backtick fences, no extra commentary.\n\n"
    + _STRUCTURE.format(related_section=_RELATED_INSTRUCTIONS)
)

SYSTEM_MD = (
    "You are a precise note-taker. Given a markdown-formatted chat log, "
    "produce a structured markdown summary.\n\n"
    "The input may use headings, bold speaker labels, or blockquotes to separate turns. "
    "Treat it as a conversation record.\n\n"
    "Return ONLY the markdown — no preamble, no backtick fences, no extra commentary.\n\n"
    + _STRUCTURE.format(related_section=_RELATED_PLACEHOLDER)
)

SYSTEM_MD_RELATED = (
    "You are a precise note-taker. Given a markdown-formatted chat log and a list of related "
    "past sessions, produce a structured markdown summary.\n\n"
    "The input may use headings, bold speaker labels, or blockquotes to separate turns. "
    "Treat it as a conversation record.\n\n"
    "Return ONLY the markdown — no preamble, no backtick fences, no extra commentary.\n\n"
    + _STRUCTURE.format(related_section=_RELATED_INSTRUCTIONS)
)


def call_ollama(prompt: str, system: str) -> str:
    payload = {"model": MODEL, "prompt": prompt, "system": system, "stream": False}
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        OLLAMA_URL,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=300) as resp:
            return json.loads(resp.read().decode("utf-8"))["response"].strip()
    except urllib.error.URLError as e:
        print(
            f"\nError: Could not reach Ollama at {OLLAMA_URL}\n"
            f"Make sure Ollama is running:  ollama serve\n"
            f"And the model is pulled:      ollama pull {MODEL}\n"
            f"Details: {e}",
            file=sys.stderr,
        )
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Summarize a chat transcript or markdown chat log using Ollama."
    )
    parser.add_argument(
        "input_file",
        help="Path to a raw transcript (.txt) or a markdown chat file (.md with --md)",
    )
    parser.add_argument(
        "--md",
        action="store_true",
        help="Input is a pre-formatted markdown chat log, not a raw USER:/ASSISTANT: transcript",
    )
    parser.add_argument(
        "--related",
        action="append",
        default=[],
        metavar="PATH|DESCRIPTION",
        help='Related session: "path/to/file.md|One-line description". Repeatable.',
    )
    args = parser.parse_args()

    input_path = Path(args.input_file)
    if not input_path.exists():
        print(f"Error: input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    content = input_path.read_text(encoding="utf-8").strip()
    if not content:
        print("Error: input file is empty.", file=sys.stderr)
        sys.exit(1)

    has_related = bool(args.related)
    related_block = "\n".join(f"  {r}" for r in args.related)

    if args.md:
        if has_related:
            system = SYSTEM_MD_RELATED
            prompt = (
                f"Summarize this markdown chat log.\n\n"
                f"Related past sessions (path|description):\n{related_block}\n\n"
                f"Chat log:\n{content}"
            )
        else:
            system = SYSTEM_MD
            prompt = f"Summarize this markdown chat log:\n\n{content}"
    else:
        if has_related:
            system = SYSTEM_RAW_RELATED
            prompt = (
                f"Summarize this chat transcript.\n\n"
                f"Related past sessions (path|description):\n{related_block}\n\n"
                f"Transcript:\n{content}"
            )
        else:
            system = SYSTEM_RAW
            prompt = f"Summarize this chat transcript:\n\n{content}"

    print(call_ollama(prompt, system))


if __name__ == "__main__":
    main()
