#!/usr/bin/env python3
"""
summarize_with_ollama.py — Summarize a raw chat transcript using a local Ollama model.

Usage:
    python scripts/summarize_with_ollama.py <transcript_file> [--related "path|description" ...]

    --related can be passed multiple times, once per related session.

Reads the transcript from the given file, sends it to gemma4:31b via Ollama,
and prints a structured markdown summary to stdout.

Requires Ollama to be running locally: https://ollama.ai
    ollama serve
    ollama pull gemma4:31b
"""

import argparse
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path
import os

_env_path = Path(__file__).parent.parent / ".env"
if _env_path.exists():
    for _line in _env_path.read_text().splitlines():
        if _line.startswith("OLLAMA_URL="):
            os.environ.setdefault("OLLAMA_URL", _line.split("=", 1)[1].strip())

OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434/api/generate")
MODEL = "gemma4:31b"

SYSTEM_PROMPT = """You are a precise note-taker. Given a raw AI chat transcript, produce a structured markdown summary.

Return ONLY the markdown — no preamble, no backtick fences, no extra commentary.

Use this exact structure:

# Chat Summary: <short topic title>

**Date:** <extract from transcript or use today>
**Session Length:** <approximate message count>

---

## Overview
<2–4 sentences describing what this session covered and why>

## Topics Discussed
- <topic 1>
- <topic 2>

## Key Outcomes
<Concrete results: files created, decisions made, problems solved. Be specific.>

## Code / Files Produced
<List any scripts, files, or artifacts with one-line descriptions. Omit section if none.>

## Related Sessions
<Placeholder — will be injected by the script if related sessions are provided. Omit section if the list below is empty.>

## Action Items / Next Steps
<Tasks the user indicated they want to do next. Omit section if none.>

---
*Summary generated by gemma4:31b via Ollama*
"""

SYSTEM_PROMPT_WITH_RELATED = """You are a precise note-taker. Given a raw AI chat transcript and a list of related past sessions, produce a structured markdown summary.

Return ONLY the markdown — no preamble, no backtick fences, no extra commentary.

Use this exact structure:

# Chat Summary: <short topic title>

**Date:** <extract from transcript or use today>
**Session Length:** <approximate message count>

---

## Overview
<2–4 sentences describing what this session covered and why>

## Topics Discussed
- <topic 1>
- <topic 2>

## Key Outcomes
<Concrete results: files created, decisions made, problems solved. Be specific.>

## Code / Files Produced
<List any scripts, files, or artifacts with one-line descriptions. Omit section if none.>

## Related Sessions
<Use the related sessions list provided to write markdown links. For each, write:
- [session-slug](relative/path.md) — one sentence on how it connects to THIS session (what came before or after, what problem it continued, etc.)
Order them chronologically if dates are available.>

## Action Items / Next Steps
<Tasks the user indicated they want to do next. Omit section if none.>

---
*Summary generated by gemma4:31b via Ollama*
"""


def call_ollama(prompt: str, system: str) -> str:
    payload = {
        "model": MODEL,
        "prompt": prompt,
        "system": system,
        "stream": False,
    }
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        OLLAMA_URL,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=300) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            return result["response"].strip()
    except urllib.error.URLError as e:
        print(
            f"\nError: Could not reach Ollama at {OLLAMA_URL}\n"
            f"Make sure Ollama is running:  ollama serve\n"
            f"And the model is pulled:      ollama pull {MODEL}\n"
            f"Details: {e}",
            file=sys.stderr,
        )
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("transcript_file", help="Path to the raw transcript .txt file")
    parser.add_argument(
        "--related",
        action="append",
        default=[],
        metavar="PATH|DESCRIPTION",
        help='Related session entry, format: "path/to/file.md|One-line description". Repeatable.',
    )
    args = parser.parse_args()

    transcript_path = Path(args.transcript_file)
    if not transcript_path.exists():
        print(f"Error: transcript file not found: {transcript_path}", file=sys.stderr)
        sys.exit(1)

    transcript = transcript_path.read_text(encoding="utf-8").strip()
    if not transcript:
        print("Error: transcript file is empty.", file=sys.stderr)
        sys.exit(1)

    if args.related:
        related_block = "\n".join(f"  {r}" for r in args.related)
        prompt = (
            f"Summarize this chat transcript.\n\n"
            f"Related past sessions in the same topic (path|description):\n{related_block}\n\n"
            f"Transcript:\n{transcript}"
        )
        summary = call_ollama(prompt, SYSTEM_PROMPT_WITH_RELATED)
    else:
        prompt = f"Summarize this chat transcript:\n\n{transcript}"
        summary = call_ollama(prompt, SYSTEM_PROMPT)

    print(summary)


if __name__ == "__main__":
    main()
