#!/usr/bin/env python3
"""
query.py — Retrieve relevant wiki pages for a question and print them for Claude Code.

Usage:
    python scripts/query.py "your question here" [--save <answer_file>]

    --save <file>   After Claude Code answers, pass the answer back to file the
                    response into the wiki as a new page.

This script does NOT call any LLM API for the answer. Instead it:
  1. Uses gemma4:31b (local) to find which topics are relevant
  2. Loads those wiki pages
  3. Prints them to stdout in a structured format

Claude Code reads the output and synthesizes the answer directly.
No API key needed.

To file an answer back into the wiki:
    python scripts/query.py --save answer.md
"""

import argparse
import re
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from config import cfg
from llm import call_local
from wiki_index import append_log, insert_entry, load_memory, slugify

RELEVANCE_SYSTEM = """\
You are a search assistant for a personal knowledge wiki.
Given a question and the wiki index (Memory.md), identify which topic sections are most relevant.
Return ONLY valid JSON, no fences:
{
  "topics": ["Topic Name 1", "Topic Name 2"],
  "reasoning": "one sentence explaining why"
}
If no topics are clearly relevant, return {"topics": [], "reasoning": "..."}
"""

SAVE_PAGE_SYSTEM = """\
You are creating a wiki page from a Q&A exchange.
Given the question and a provided answer, write a clean wiki page that stands alone as a reference.

Return ONLY markdown, no fences:

# <Question as title>

**Date:** <today>
**Type:** Query

---

## Answer
<Clean version of the answer>

## Sources Used
<List of wiki pages cited, if known>

## Related Pages
<Leave blank>

---
*Generated by brain-wiki query*
"""


def find_relevant_topics(question: str, memory_text: str) -> list[str]:
    prompt = f"Question: {question}\n\nMemory.md:\n{memory_text}"
    raw = call_local(prompt, RELEVANCE_SYSTEM, timeout=60)
    raw = re.sub(r"```[a-z]*\n?", "", raw).strip()
    try:
        import json
        result = json.loads(raw)
        topics = result.get("topics", [])
        reasoning = result.get("reasoning", "")
        if reasoning:
            print(f"  Relevance: {reasoning}", file=sys.stderr)
        return topics
    except Exception:
        return []


def load_topic_pages(topics: list[str], memory_text: str) -> list[tuple[str, str]]:
    """Load wiki pages for the given topics. Returns [(slug, content)]."""
    pages = []
    # Load _overview.md first for context
    for topic in topics:
        overview = cfg.wiki_dir / slugify(topic) / "_overview.md"
        if overview.exists():
            content = overview.read_text(encoding="utf-8")
            pages.append((f"[overview] {topic}", content))

    # Load individual pages
    current_topic = None
    in_relevant = False
    for line in memory_text.splitlines():
        if line.startswith("## "):
            current_topic = line[3:].strip()
            in_relevant = not topics or current_topic in topics
            continue
        if in_relevant:
            m = re.match(r"-\s+\[([^\]]+)\]\(([^)]+)\)", line)
            if m:
                page_path = cfg.vault_root / m.group(2)
                if page_path.exists():
                    content = page_path.read_text(encoding="utf-8")
                    pages.append((m.group(1), content))

    return pages


def save_answer(question: str, answer_file: Path):
    """File an answer back into the wiki."""
    if not answer_file.exists():
        print(f"Error: answer file not found: {answer_file}", file=sys.stderr)
        sys.exit(1)

    answer_text = answer_file.read_text(encoding="utf-8").strip()
    today = date.today().isoformat()
    slug = re.sub(r"[^a-z0-9]+", "-", question.lower())[:40].strip("-")
    slug = f"query-{slug}-{today}"

    topic = "Queries & Synthesis"
    topic_folder = slugify(topic)
    topic_dir = cfg.wiki_dir / topic_folder
    topic_dir.mkdir(parents=True, exist_ok=True)

    prompt = f"Question: {question}\n\nAnswer:\n{answer_text}\n\nToday: {today}"
    page_content = call_local(prompt, SAVE_PAGE_SYSTEM, timeout=180)

    page_path = topic_dir / f"{slug}.md"
    page_path.write_text(page_content, encoding="utf-8")

    memory_text = load_memory(cfg.memory_md)
    rel = page_path.relative_to(cfg.vault_root)
    memory_entry = f"- [{slug}]({rel}) — Q: {question[:60]}"
    updated = insert_entry(memory_text, topic, memory_entry, today)
    cfg.memory_md.write_text(updated, encoding="utf-8")

    append_log(cfg.log_md, "query-saved", f"{question[:60]} → {slug}.md")
    print(f"✓ Answer filed: wiki/{topic_folder}/{slug}.md")


def main():
    parser = argparse.ArgumentParser(description="Retrieve wiki pages for a question")
    parser.add_argument("question", nargs="?", help="Your question")
    parser.add_argument("--save", metavar="ANSWER_FILE",
                        help="File an answer back into the wiki (provide answer as a .md file)")
    args = parser.parse_args()

    cfg.ensure_dirs()

    # --save mode: just file the answer, no retrieval needed
    if args.save and not args.question:
        print("Error: --save requires a question as the first argument", file=sys.stderr)
        sys.exit(1)

    if args.save and args.question:
        save_answer(args.question, Path(args.save))
        return

    if not args.question:
        parser.print_help()
        sys.exit(1)

    memory_text = load_memory(cfg.memory_md)

    print(f"\nFinding relevant topics for: {args.question}", file=sys.stderr)
    topics = find_relevant_topics(args.question, memory_text)

    pages = load_topic_pages(topics, memory_text)

    if not pages:
        print("\n── BRAIN WIKI CONTEXT ──────────────────────────────────────")
        print(f"No relevant pages found for: {args.question}")
        print("The wiki may not have sources on this topic yet.")
        print("Consider ingesting relevant sources first.")
        print("────────────────────────────────────────────────────────────")
        append_log(cfg.log_md, "query", f"(no results) {args.question[:80]}")
        return

    # Print pages for Claude Code to read and synthesize
    print("\n── BRAIN WIKI CONTEXT ──────────────────────────────────────")
    print(f"Question: {args.question}")
    print(f"Pages loaded: {len(pages)}")
    print("────────────────────────────────────────────────────────────\n")

    for slug, content in pages:
        print(f"=== {slug} ===")
        print(content)
        print()

    print("── END BRAIN WIKI CONTEXT ──────────────────────────────────")
    print("Synthesize an answer to the question above using these pages.")
    print("Cite page names where relevant. If pages are insufficient, say so.")
    print("────────────────────────────────────────────────────────────")

    append_log(cfg.log_md, "query", args.question[:80])


if __name__ == "__main__":
    main()
